<?php if (!empty($this->paginator)) : ?>
    <div id="supplier-content">
        <table class="table table-striped">
                <tr>
                    <th>Supplier name</th>
                    <th>Address Line 1</th>
                    <th>Address Line 2</th>
                    <th>Town</th>
                    <th>Post Code</th>
                    <th>Telephone</th>
                    <th>Fax</th>
                    <th>Email</th>
                    <th>Action</th>
                </tr>
        <?php foreach ($this->paginator as $supplier) : ?>
            <tr>
                <td><?=$this->escapeHtml($supplier->getSupplierName())?></td>
                <td><?=$this->escapeHtml($supplier->getAddress()->getAddressLine1())?></td>
                <td><?=$this->escapeHtml($supplier->getAddress()->getAddressLine2())?></td>
                <td><?=$this->escapeHtml($supplier->getAddress()->getTown())?></td>
                <td><?=$this->escapeHtml($supplier->getAddress()->getPostCode())?></td>
                <td><?=$this->escapeHtml($supplier->getAddress()->getTelephone())?></td>
                <td><?=$this->escapeHtml($supplier->getAddress()->getFax())?></td>
                <td><?=$this->escapeHtml($supplier->getAddress()->getEmail())?></td>
                <td><select>
                        <option></option>
                        <option>edit</option>
                        <option>delete</option>
                    </select>
                </td>
            </tr>
        <?php endforeach; ?>
        </table>
    </div>
<?php else : ?>
    <p><?php echo $this->translate('There are currently no articles.'); ?></p>
<?php endif; ?>